config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  # root 'songs#index'
  post 'stuff' => 'splash#stuff', as: :stuff

  get  'songs/index'  => 'songs#index',  as: :songs
  post 'songs/upload' => 'songs#upload', as: :upload
  get  'songs/delete' => 'songs#delete', as: :delete
  get  'songs/purchase'   => 'songs#purchase',   as: :purchase

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = AWS::S3::Bucket.find(Macmccain::BUCKET, prefix: 'foo').objects
    binding.pry
    puts 'hi'
  end

  def upload
    begin
      AWS::S3::S3Object.store(
        sanitize_filename(params[:mp3file].original_filename),
        params[:mp3file].read,
        Macmccain::BUCKET,
        access: :public_read
      )
      redirect_to root_path
    rescue
      render text: "Couldn't complete the upload"
    end
  end

  def delete
    if params[:song]
      AWS::S3::S3Object.find(params[:song], Macmccain::BUCKET).delete
      redirect_to root_path
    else
      render text: "No song was found to delete"
    end
  end

  def purchase
    redirect_to songs_path
  end

  private

  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/, '-')
  end

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController

  def index
    # binding.pry
  end

  def stuff
    redirect_to paypal_url("/")
  end

  private

  def paypal_url(return_path)
    values = {
        business: "bpwalford-facilitator@gmail.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        amount: 12.34,
        item_name: "songs item",
        item_number: 7676,
        quantity: '1'
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def download_url_for(song_key)
    AWS::S3::S3Object.url_for(song_key, Macmccain::BUCKET, authenticated: false)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Macmccain</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<h2>Upload a new MP3:</h2>
<%= form_tag upload_path, method: "post", multipart: true do %>
  <%= file_field_tag "mp3file" %>
  <%= submit_tag "upload" %>
<% end %>

<h2>Download and Delete Existing MP3's</h2>
<table>
<% @songs.each do |song| %>
    <tr>
        <td><%= song.key %></td>
        <td><%= link_to "delete", delete_path(song: song.key), confirm: "Are you sure?" %></td>
        <td><%= link_to "Download", download_url_for(song.key) %></td>
    </tr>
<% end %>
</table>